CUDA_VISIBLE_DEVICES=0,1 python3 main.py \
  --synthetic_train_data_dir /home/aster.pytorch/lmdb_test \
  --test_data_dir /home/aster.pytorch/lmdb_test \
  --batch_size 5 \
  --workers 8 \
  --height 64 \
  --width 256 \
  --voc_type ALLCASES_SYMBOLS \
  --arch ResNet_ASTER \
  --with_lstm \
  --logs_dir /home/aster.pytorch/train_logs \
  --real_logs_dir /home/aster.pytorch/train_logs_real \
  --max_len 100 \
  --STN_ON \
  --tps_inputsize 32 64 \
  --tps_outputsize 32 100 \
  --tps_margins 0.05 0.05 \
  --stn_activation none \
  --num_control_points 20 \
